class Sum { 
	public static void main(String[] a) {
        System.out.println(new Doit().doit(101));
    }
}

class Doit {
    public int doit(int n) {
        int sum;
        int i;
        
        i = 0;
        sum = 0;
        while (i<n){
        	sum = sum + i;
        	i = i+1;
        }
        return sum;
    }
}


/***************
TOKEN_CLASS TOKEN_ID TOKEN_LBRACE 
TOKEN_PUBLIC TOKEN_STATIC TOKEN_VOID TOKEN_MAIN TOKEN_LPAREN TOKEN_STRING TOKEN_LBRACK TOKEN_RBRACK TOKEN_ID TOKEN_RPAREN TOKEN_LBRACE 
TOKEN_SYSTEM TOKEN_DOT TOKEN_OUT TOKEN_DOT TOKEN_PRINTLN TOKEN_LPAREN TOKEN_NEW TOKEN_ID TOKEN_LPAREN TOKEN_RPAREN TOKEN_DOT TOKEN_ID TOKEN_LPAREN TOKEN_NUM TOKEN_RPAREN TOKEN_RPAREN TOKEN_SEMI 
TOKEN_RBRACE 
TOKEN_RBRACE 
TOKEN_CLASS TOKEN_ID TOKEN_LBRACE 
TOKEN_PUBLIC TOKEN_INT TOKEN_ID TOKEN_LPAREN TOKEN_INT TOKEN_ID TOKEN_RPAREN TOKEN_LBRACE 
TOKEN_INT TOKEN_ID TOKEN_SEMI 
TOKEN_INT TOKEN_ID TOKEN_SEMI 
TOKEN_ID TOKEN_ASSIGN TOKEN_NUM TOKEN_SEMI 
TOKEN_ID TOKEN_ASSIGN TOKEN_NUM TOKEN_SEMI 
TOKEN_WHILE TOKEN_LPAREN TOKEN_ID TOKEN_LT TOKEN_ID TOKEN_RPAREN TOKEN_LBRACE 
TOKEN_ID TOKEN_ASSIGN TOKEN_ID TOKEN_ADD TOKEN_ID TOKEN_SEMI 
TOKEN_ID TOKEN_ASSIGN TOKEN_ID TOKEN_ADD TOKEN_NUM TOKEN_SEMI 
TOKEN_RBRACE 
TOKEN_RETURN TOKEN_ID TOKEN_SEMI 
TOKEN_RBRACE 
TOKEN_RBRACE 

****************/